default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: shubham
  password:

development:
  <<: *default
  database: development_Minstant

test:
  <<: *default
  database: test_Minstant

production:
  <<: *default
  database: production_Minstant
